HaberSitesi2/HaberSitesi.MvcWebUI/Controllers/AnasayfaController.cs
using HaberSitesi.Business.Concrete;
using HaberSitesi.DataAccess.Concrete.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HaberSitesi.MvcWebUI.Controllers
{
    public class AnasayfaController : Controller
    {
        NewsManager newsManager = new NewsManager(new EfNewsDal());
        WriterManager writerManager = new WriterManager(new EfWriterDal());
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult SonDakika()
        {
            var values = newsManager.GetList().Take(10).ToList();
            return PartialView(values);
        }
        public PartialViewResult Slider()
        {
            var values = newsManager.GetList().Take(10).ToList();
            return PartialView(values);
        }
        public PartialViewResult SonHaberler()
        {
            var values = newsManager.GetList().Take(5).ToList();
            return PartialView(values);
        }
        public PartialViewResult Spor()
        {
            var values = newsManager.GetSportList().Take(4).ToList();
            return PartialView(values);
        }
        public PartialViewResult Saglik()
        {
            var values = newsManager.GetHealthList().Take(4).ToList();
            return PartialView(values);
        }
        public PartialViewResult Ekonomi()
        {
            var values = newsManager.GetEconomyList().Take(4).ToList();
            return PartialView(values);
        }
        public PartialViewResult EkonomiEk()
        {
            var values = newsManager.GetEconomyList().Take(1).ToList();
            return PartialView(values);
        }
        public PartialViewResult Dunya()
        {
            var values = newsManager.GetWorldList().Take(4).ToList();
            return PartialView(values);
        }
        public PartialViewResult DunyaEk()
        {
            var values = newsManager.GetWorldList().Take(1).ToList();
            return PartialView(values);
        }
        public PartialViewResult Yazarlar()
        {
            var values = writerManager.GetList().Take(4).ToList();
            return PartialView(values);
        }
        public PartialViewResult Gundem()
        {
            var values = newsManager.GetAgendaList().Take(4).ToList();
            return PartialView(values);
        }
        public PartialViewResult GundemEk()
        {
            var values = newsManager.GetAgendaList().Take(1).ToList();
            return PartialView(values);
        }
        public PartialViewResult Teknoloji()
        {
            var values = newsManager.GetTechnologyList().Take(3).ToList();
            return PartialView(values);
        }
        public PartialViewResult TeknolojiEk()
        {
            var values = newsManager.GetTechnologyList().Take(1).ToList();
            return PartialView(values);
        }
    }
}

HaberSitesi2/HaberSitesi.MvcWebUI/Controllers/TeknolojiController.cs
using HaberSitesi.Business.Concrete;
using HaberSitesi.DataAccess.Concrete.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HaberSitesi.MvcWebUI.Controllers
{
    public class TeknolojiController : Controller
    {
        NewsManager newsManager = new NewsManager(new EfNewsDal());
        public ActionResult Index()
        {
            var newsValues = newsManager.GetTechnologyList();
            return View(newsValues);
        }
        public ActionResult Haber(int id)
        {
            var newsValues = newsManager.GetByID(id);
            return View(newsValues);
        }
    }
}

HaberSitesi2/HaberSitesi.MvcWebUI/Views/Teknoloji/Haber.cshtml
@model HaberSitesi.Entities.Concrete.News
@{
    ViewBag.Title = "Haber";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <section id="contentSection">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8">
                <div class="left_content">
                    <div class="single_page">
                        <ol class="breadcrumb">
                            <li><a href="/Teknoloji/Index">Teknoloji Haberleri</a></li>
                            <li class="active" style="color:white">@Model.NewsTitle</li>
                        </ol>
                        <h1>@Model.NewsTitle</h1>
                        <div class="post_commentbox"> <a href="#"><i class="fa fa-user"></i>@Model.Writer.WriterName @Model.Writer.WriterSurname</a> <span><i class="fa fa-calendar"></i>@Model.NewsDate.ToShortDateString()</span> <a href="#"><i class="fa fa-tags"></i>@Model.Category.CategoryName</a> </div>
                        <div class="single_page_content">
                            <img class="img-center" src="@Model.NewsImage" alt="">
                            <p>@Model.NewsContent</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4">
                @Html.Action("SonHaberler", "Anasayfa")
                @Html.Action("Spor", "Anasayfa")
            </div>
        </div>
    </section>
</div>

HaberSitesi2/HaberSitesi.MvcWebUI/Views/Teknoloji/Index.cshtml
@using HaberSitesi.Entities.Concrete
@model List<News>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="contentSection">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="single_page">
                <ol class="breadcrumb">
                    <li><a href="/Teknoloji/Index">Teknoloji Haberleri</a></li>
                </ol>
                @foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <div class="single_post_content">
                            <ul class="business_catgnav wow fadeInDown">
                                <li>
                                    <figure class="bsbig_fig">
                                        <a href="/Teknoloji/Haber/@item.NewsID" class="featured_img"> <img alt="" src="@item.NewsImage" style="width:330px; height:170px;"> <span class="overlay"></span> </a>
                                        <figcaption> <a href="/Teknoloji/Haber/@item.NewsID">@item.NewsTitle</a> </figcaption>
                                        <p>@item.NewsContent.Substring(0, 90)...</p>
                                    </figure>
                                </li>
                            </ul>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>